const starterLessons=[
{id:"math",subject:"Mathematics",icon:"➗",title:"Fractions and percentages",exams:["WAEC","NECO","JAMB"],summary:"Work with fractions, decimals and percentages.",body:"Fractions\nA fraction shows part of a whole. For example, 1/2 + 1/4 = 2/4 + 1/4 = 3/4.\n\nPercentages\nPercent means out of 100. To find 20% of 150, calculate 20 ÷ 100 × 150 = 30."},
{id:"english",subject:"English Language",icon:"📖",title:"Reading comprehension",exams:["WAEC","NECO","JAMB"],summary:"Find the main idea, details and meaning from context.",body:"Comprehension tips\n1. Read the passage carefully.\n2. Use the passage as evidence.\n3. For a word's meaning, read the surrounding sentence."},
{id:"biology",subject:"Biology",icon:"🧬",title:"The cell and its parts",exams:["WAEC","NECO","JAMB"],summary:"Learn the basic unit of life and the functions of cell parts.",body:"What is a cell?\nA cell is the basic structural and functional unit of life.\n\nCell membrane: controls what enters and leaves.\nNucleus: contains genetic material.\nCytoplasm: where many reactions take place.\nMitochondria: release usable energy."}
];
const quizzes={
"Mathematics":[{q:"What is 20% of 150?",o:["15","20","30","50"],a:2,w:"20/100 × 150 = 30."},{q:"What is 1/2 + 1/4?",o:["2/6","3/4","1/6","2/4"],a:1,w:"Convert 1/2 to 2/4, then add to get 3/4."},{q:"Solve 5 × (3 + 2).",o:["17","25","13","10"],a:1,w:"Calculate inside brackets first: 5 × 5 = 25."}],
"English Language":[{q:"Which word is closest in meaning to rapid?",o:["Slow","Quick","Quiet","Weak"],a:1,w:"Rapid means fast or quick."},{q:"Choose the correct sentence.",o:["She go to school.","She going school.","She goes to school.","She gone to school."],a:2,w:"With she in the simple present tense, use goes."},{q:"A paragraph's main idea is:",o:["Its central point","The longest word","The final punctuation","The title only"],a:0,w:"The main idea is the central point."}],
"Biology":[{q:"What is the basic unit of life?",o:["Organ","Cell","Tissue","System"],a:1,w:"The cell is the basic structural and functional unit of life."},{q:"Which cell part controls what enters and leaves?",o:["Nucleus","Cell membrane","Ribosome","Vacuole"],a:1,w:"The cell membrane regulates movement into and out of the cell."},{q:"Which organelle is associated with energy release?",o:["Mitochondrion","Cell wall","Chloroplast only","Nucleus"],a:0,w:"Mitochondria are major sites of aerobic respiration."}]
};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const readStore=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch{return d}};
const writeStore=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let customLessons=readStore("smartlearn-custom-lessons",[]),lessons=[...starterLessons,...customLessons];
let saved=readStore("smartlearn-saved",[]),results=readStore("smartlearn-results",[]),profile=readStore("smartlearn-profile",{name:"",exam:"WAEC"}),exam="All",active=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const bodyHtml=s=>esc(s).replace(/\n/g,"<br>");
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function examsText(l){return l.exams.join(" · ")}
function renderLessons(){const term=$("#searchInput").value.trim().toLowerCase();const list=lessons.filter(l=>(exam==="All"||l.exams.includes(exam))&&(l.title+" "+l.subject+" "+l.summary).toLowerCase().includes(term));$("#lessonGrid").innerHTML=list.map(l=>'<article class="lesson-card"><div class="lesson-top"><span class="subject-icon">'+esc(l.icon||"📘")+'</span><span class="tag">'+esc(examsText(l))+'</span></div><h3>'+esc(l.title)+'</h3><p>'+esc(l.summary)+'</p><div class="lesson-meta"><button class="text-btn" data-read="'+esc(l.id)+'">Read lesson →</button><button class="save-btn '+(saved.includes(l.id)?"saved":"")+'" data-save="'+esc(l.id)+'">'+(saved.includes(l.id)?"✓ Saved":"＋ Save lesson")+'</button></div></article>').join("");$("#emptyState").hidden=list.length>0;$("#subjectCount").textContent=new Set(lessons.map(l=>l.subject)).size}
function renderSaved(){const list=saved.map(id=>lessons.find(l=>l.id===id)).filter(Boolean);$("#savedLessons").innerHTML=list.length?list.map(l=>'<article class="saved-item"><div><strong>'+esc(l.title)+'</strong><p>'+esc(l.subject)+' · Saved on this device</p></div><div><button class="text-btn" data-read="'+esc(l.id)+'">Open</button> <button class="text-btn" data-remove="'+esc(l.id)+'">Remove</button></div></article>').join(""):'<p class="muted">No saved lessons yet. Choose a lesson and tap Save lesson.</p>'}
function renderManaged(){const list=customLessons;$("#managedLessons").innerHTML=list.length?list.map(l=>'<article class="managed-item"><div><strong>'+esc(l.title)+'</strong><p>'+esc(l.subject)+' · '+esc(examsText(l))+'</p></div><button class="btn secondary" data-delete-lesson="'+esc(l.id)+'">Delete</button></article>').join(""):'<p class="muted">No custom lessons added yet.</p>'}
function renderHistory(){$("#quizHistory").innerHTML=results.length?results.slice(0,8).map(r=>'<div class="history-row"><span><strong>'+esc(r.subject)+'</strong><small>'+esc(new Date(r.date).toLocaleDateString())+'</small></span><strong>'+r.score+'/'+r.total+' · '+r.percent+'%</strong></div>').join(""):'<p class="muted">Your completed quizzes will appear here.</p>';$("#heroCompleted").textContent=results.filter(r=>r.percent>=70).length}
function renderProfile(){$("#studentName").value=profile.name||"";$("#studentExam").value=profile.exam||"WAEC";$("#profileGreeting").textContent=profile.name?"Welcome back, "+profile.name+"! Goal: "+profile.exam+".":"Welcome to your study space."}
function renderQuizSubjects(){const selected=$("#quizSubject").value;const subjects=[...new Set(lessons.map(l=>l.subject))];$("#quizSubject").innerHTML=subjects.map(s=>'<option>'+esc(s)+'</option>').join("");if(subjects.includes(selected))$("#quizSubject").value=selected}
function saveLesson(id){if(!saved.includes(id))saved.push(id);writeStore("smartlearn-saved",saved);renderLessons();renderSaved();toast("Lesson saved on this device.")}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;const w=window.open("","_blank");if(!w){toast("Allow pop-ups to open a lesson.");return}w.document.write('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(l.title)+' — SmartLearn</title><style>body{font:17px/1.8 system-ui,sans-serif;max-width:720px;margin:36px auto;padding:0 20px;color:#182230}a{color:#155eef}</style></head><body><p>SMARTLEARN · '+esc(l.subject)+' · '+esc(examsText(l))+'</p><h1>'+esc(l.title)+'</h1><p>'+esc(l.summary)+'</p><article>'+bodyHtml(l.body)+'</article><hr><a href="'+location.href+'">← Back to SmartLearn</a></body></html>');w.document.close()}
function startQuiz(){const subject=$("#quizSubject").value,qs=quizzes[subject];if(!qs){$("#quizArea").innerHTML='<p class="muted">A quiz for this subject has not been added yet. Add quiz questions in a future content update.</p>';return}active={subject,qs};let html='<form id="quizForm"><p class="eyebrow">PRACTICE QUIZ · '+esc(subject)+'</p>';qs.forEach((q,i)=>{html+='<section class="question"><h4>'+(i+1)+'. '+esc(q.q)+'</h4>';q.o.forEach((o,j)=>{html+='<label class="option"><input type="radio" name="q'+i+'" value="'+j+'" required> '+esc(o)+'</label>'});html+='</section>'});html+='<button class="btn primary" type="submit">Submit answers</button></form>';$("#quizArea").innerHTML=html;$("#quizForm").addEventListener("submit",submitQuiz)}
function submitQuiz(e){e.preventDefault();const data=new FormData(e.target);let score=0;const qs=active.qs;let html="";qs.forEach((q,i)=>{const correct=Number(data.get("q"+i))===q.a;if(correct)score++;html+='<section class="question"><h4>'+(i+1)+'. '+esc(q.q)+'</h4><p><b>'+(correct?"Correct":"Review this answer")+'</b> · Correct answer: '+esc(q.o[q.a])+'</p><p class="explanation">'+esc(q.w)+'</p></section>'});const percent=Math.round(score/qs.length*100);results.unshift({subject:active.subject,score,total:qs.length,percent,date:new Date().toISOString()});results=results.slice(0,50);writeStore("smartlearn-results",results);renderHistory();$("#quizArea").innerHTML='<div class="result-box"><h3>Quiz complete: '+score+'/'+qs.length+' ('+percent+'%)</h3><p>'+(percent>=70?"Good work! Review the explanations.":"Keep practising and try again.")+'</p></div>'+html+'<button id="retryQuiz" class="btn primary">Try again</button>';$("#retryQuiz").addEventListener("click",startQuiz)}
$("#lessonGrid").addEventListener("click",e=>{const r=e.target.closest("[data-read]"),s=e.target.closest("[data-save]");if(r)openLesson(r.dataset.read);if(s){const id=s.dataset.save;if(saved.includes(id)){saved=saved.filter(x=>x!==id);writeStore("smartlearn-saved",saved);renderLessons();renderSaved()}else saveLesson(id)}});
$("#savedLessons").addEventListener("click",e=>{const r=e.target.closest("[data-read]"),d=e.target.closest("[data-remove]");if(r)openLesson(r.dataset.read);if(d){saved=saved.filter(x=>x!==d.dataset.remove);writeStore("smartlearn-saved",saved);renderSaved();renderLessons()}});
$("#managedLessons").addEventListener("click",e=>{const b=e.target.closest("[data-delete-lesson]");if(!b)return;customLessons=customLessons.filter(l=>l.id!==b.dataset.deleteLesson);writeStore("smartlearn-custom-lessons",customLessons);lessons=[...starterLessons,...customLessons];saved=saved.filter(id=>lessons.some(l=>l.id===id));writeStore("smartlearn-saved",saved);renderAll();toast("Custom lesson removed from this device.")});
$("#examFilters").addEventListener("click",e=>{const b=e.target.closest("[data-exam]");if(!b)return;exam=b.dataset.exam;$$(".filter").forEach(x=>x.classList.toggle("active",x===b));renderLessons()});
$("#searchInput").addEventListener("input",renderLessons);$("#startQuiz").addEventListener("click",startQuiz);$("#menuBtn").addEventListener("click",()=>$("#navLinks").classList.toggle("open"));$("#navLinks").addEventListener("click",e=>{if(e.target.tagName==="A")$("#navLinks").classList.remove("open")});
$("#profileForm").addEventListener("submit",e=>{e.preventDefault();profile={name:$("#studentName").value.trim(),exam:$("#studentExam").value};writeStore("smartlearn-profile",profile);renderProfile();toast("Profile saved on this device.")});
$("#lessonForm").addEventListener("submit",e=>{e.preventDefault();const title=$("#newTitle").value.trim(),subject=$("#newSubject").value.trim(),summary=$("#newSummary").value.trim(),body=$("#newBody").value.trim();if(!title||!subject||!summary||!body)return;const exams=$("#newExam").value.split(",").map(s=>s.trim());customLessons.unshift({id:"custom-"+Date.now().toString(36),subject,icon:"📘",title,exams,summary,body});writeStore("smartlearn-custom-lessons",customLessons);lessons=[...starterLessons,...customLessons];e.target.reset();renderAll();toast("Lesson added to this device.")});
function downloadJson(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
$("#downloadLessons").addEventListener("click",()=>downloadJson("smartlearn-custom-lessons.json",customLessons));
$("#exportData").addEventListener("click",()=>downloadJson("smartlearn-study-backup.json",{profile,saved,results,customLessons,exportedAt:new Date().toISOString()}));
function renderAll(){renderLessons();renderSaved();renderManaged();renderHistory();renderProfile();renderQuizSubjects()}
renderAll();
if("serviceWorker" in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));