const lessons=[
{id:"math",subject:"Mathematics",icon:"➗",title:"Fractions and percentages",exams:["WAEC","NECO","JAMB"],summary:"Work with fractions, decimals and percentages.",body:"<h3>Fractions</h3><p>A fraction shows part of a whole. For example, 1/2 + 1/4 = 2/4 + 1/4 = 3/4.</p><h3>Percentages</h3><p>Percent means out of 100. To find 20% of 150, calculate 20 ÷ 100 × 150 = 30.</p>"},
{id:"english",subject:"English Language",icon:"📖",title:"Reading comprehension",exams:["WAEC","NECO","JAMB"],summary:"Find the main idea, details and meaning from context.",body:"<h3>Comprehension tips</h3><ul><li>Read the passage carefully.</li><li>Use the passage as evidence.</li><li>For a word's meaning, read the surrounding sentence.</li></ul>"},
{id:"biology",subject:"Biology",icon:"🧬",title:"The cell and its parts",exams:["WAEC","NECO","JAMB"],summary:"Learn the basic unit of life and the functions of cell parts.",body:"<h3>What is a cell?</h3><p>A cell is the basic structural and functional unit of life.</p><ul><li><b>Cell membrane:</b> controls what enters and leaves.</li><li><b>Nucleus:</b> contains genetic material.</li><li><b>Cytoplasm:</b> where many reactions take place.</li><li><b>Mitochondria:</b> release usable energy.</li></ul>"}
];
const quizzes={
"Mathematics":[{q:"What is 20% of 150?",o:["15","20","30","50"],a:2,w:"20/100 × 150 = 30."},{q:"What is 1/2 + 1/4?",o:["2/6","3/4","1/6","2/4"],a:1,w:"Convert 1/2 to 2/4, then add to get 3/4."},{q:"Solve 5 × (3 + 2).",o:["17","25","13","10"],a:1,w:"Calculate inside brackets first: 5 × 5 = 25."}],
"English Language":[{q:"Which word is closest in meaning to rapid?",o:["Slow","Quick","Quiet","Weak"],a:1,w:"Rapid means fast or quick."},{q:"Choose the correct sentence.",o:["She go to school.","She going school.","She goes to school.","She gone to school."],a:2,w:"With she in the simple present tense, use goes."},{q:"A paragraph's main idea is:",o:["Its central point","The longest word","The final punctuation","The title only"],a:0,w:"The main idea is the central point."}],
"Biology":[{q:"What is the basic unit of life?",o:["Organ","Cell","Tissue","System"],a:1,w:"The cell is the basic structural and functional unit of life."},{q:"Which cell part controls what enters and leaves?",o:["Nucleus","Cell membrane","Ribosome","Vacuole"],a:1,w:"The cell membrane regulates movement into and out of the cell."},{q:"Which organelle is associated with energy release?",o:["Mitochondrion","Cell wall","Chloroplast only","Nucleus"],a:0,w:"Mitochondria are major sites of aerobic respiration."}]
};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const readStore=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
let saved=readStore("smartlearn-saved",[]),results=readStore("smartlearn-results",[]),exam="All",active=null;
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function renderLessons(){const term=$("#searchInput").value.trim().toLowerCase();const list=lessons.filter(l=>(exam==="All"||l.exams.includes(exam))&&(l.title+" "+l.subject+" "+l.summary).toLowerCase().includes(term));$("#lessonGrid").innerHTML=list.map(l=>'<article class="lesson-card"><div class="lesson-top"><span class="subject-icon">'+l.icon+'</span><span class="tag">'+l.exams.join(" · ")+'</span></div><h3>'+l.title+'</h3><p>'+l.summary+'</p><div class="lesson-meta"><button class="text-btn" data-read="'+l.id+'">Read lesson →</button><button class="save-btn '+(saved.includes(l.id)?"saved":"")+'" data-save="'+l.id+'">'+(saved.includes(l.id)?"✓ Saved":"＋ Save lesson")+'</button></div></article>').join("");$("#emptyState").hidden=list.length>0}
function renderSaved(){const list=saved.map(id=>lessons.find(l=>l.id===id)).filter(Boolean);$("#savedLessons").innerHTML=list.length?list.map(l=>'<article class="saved-item"><div><strong>'+l.title+'</strong><p>'+l.subject+' · Saved on this device</p></div><div><button class="text-btn" data-read="'+l.id+'">Open</button> <button class="text-btn" data-remove="'+l.id+'">Remove</button></div></article>').join(""):'<p class="muted">No saved lessons yet. Choose a lesson and tap Save lesson.</p>'}
function saveLesson(id){if(!saved.includes(id))saved.push(id);localStorage.setItem("smartlearn-saved",JSON.stringify(saved));renderLessons();renderSaved();toast("Lesson saved on this device.")}
function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;const w=window.open("","_blank");if(!w){toast("Allow pop-ups to open a lesson.");return}w.document.write('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+l.title+' — SmartLearn</title><style>body{font:17px/1.7 system-ui,sans-serif;max-width:720px;margin:36px auto;padding:0 20px;color:#182230}a{color:#155eef}</style></head><body><p>SMARTLEARN · '+l.subject+'</p><h1>'+l.title+'</h1><p>'+l.summary+'</p>'+l.body+'<hr><a href="'+location.href+'">← Back to SmartLearn</a></body></html>');w.document.close()}
function startQuiz(){const subject=$("#quizSubject").value,qs=quizzes[subject];active={subject:subject,qs:qs};let html='<form id="quizForm"><p class="eyebrow">PRACTICE QUIZ · '+subject+'</p>';qs.forEach((q,i)=>{html+='<section class="question"><h4>'+(i+1)+'. '+q.q+'</h4>';q.o.forEach((o,j)=>{html+='<label class="option"><input type="radio" name="q'+i+'" value="'+j+'" required> '+o+'</label>'});html+='</section>'});html+='<button class="btn primary" type="submit">Submit answers</button></form>';$("#quizArea").innerHTML=html;$("#quizForm").addEventListener("submit",submitQuiz)}
function submitQuiz(e){e.preventDefault();const data=new FormData(e.target);let score=0;const qs=active.qs;let html="";qs.forEach((q,i)=>{const correct=Number(data.get("q"+i))===q.a;if(correct)score++;html+='<section class="question"><h4>'+(i+1)+'. '+q.q+'</h4><p><b>'+(correct?"Correct":"Review this answer")+'</b> · Correct answer: '+q.o[q.a]+'</p><p class="explanation">'+q.w+'</p></section>'});const percent=Math.round(score/qs.length*100);results.unshift({subject:active.subject,score:score,total:qs.length,percent:percent,date:new Date().toISOString()});results=results.slice(0,20);localStorage.setItem("smartlearn-results",JSON.stringify(results));$("#heroCompleted").textContent=results.filter(r=>r.percent>=70).length;$("#quizArea").innerHTML='<div class="result-box"><h3>Quiz complete: '+score+'/'+qs.length+' ('+percent+'%)</h3><p>'+(percent>=70?"Good work! Review the explanations.":"Keep practising and try again.")+'</p></div>'+html+'<button id="retryQuiz" class="btn primary">Try again</button>';$("#retryQuiz").addEventListener("click",startQuiz)}
$("#lessonGrid").addEventListener("click",e=>{const r=e.target.closest("[data-read]"),s=e.target.closest("[data-save]");if(r)openLesson(r.dataset.read);if(s){const id=s.dataset.save;if(saved.includes(id)){saved=saved.filter(x=>x!==id);localStorage.setItem("smartlearn-saved",JSON.stringify(saved));renderLessons();renderSaved()}else saveLesson(id)}});
$("#savedLessons").addEventListener("click",e=>{const r=e.target.closest("[data-read]"),d=e.target.closest("[data-remove]");if(r)openLesson(r.dataset.read);if(d){saved=saved.filter(x=>x!==d.dataset.remove);localStorage.setItem("smartlearn-saved",JSON.stringify(saved));renderSaved();renderLessons()}});
$("#examFilters").addEventListener("click",e=>{const b=e.target.closest("[data-exam]");if(!b)return;exam=b.dataset.exam;$$(".filter").forEach(x=>x.classList.toggle("active",x===b));renderLessons()});
$("#searchInput").addEventListener("input",renderLessons);$("#startQuiz").addEventListener("click",startQuiz);$("#menuBtn").addEventListener("click",()=>$("#navLinks").classList.toggle("open"));$("#navLinks").addEventListener("click",e=>{if(e.target.tagName==="A")$("#navLinks").classList.remove("open")});
$("#heroCompleted").textContent=results.filter(r=>r.percent>=70).length;renderLessons();renderSaved();
if("serviceWorker" in navigator&&(location.protocol==="https:"||location.hostname==="localhost"))window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));